package config

// serverOptionCN 为 servertest.ini 的服务端配置键提供中文名称。
// 面板展示 label 时，会优先使用游戏自带的翻译文件；
// 游戏翻译文件未覆盖的键，则回退使用这里的中文映射。
// 前端显示为“键名 + 中文”，方便对照理解。
var serverOptionCN = map[string]string{
	// ---- 玩家与 PVP ----
	"PVP":              "玩家对战",
	"PVPLogToolChat":   "PVP击杀聊天播报",
	"PVPLogToolFile":   "PVP击杀日志写入文件",
	"Pausable":         "玩家加入时暂停服务器",
	"AllowPlayersToSeeWholeMap": "允许玩家查看全图",
	"Public":           "服务器公开可见",
	"PublicDescription": "服务器公开描述",
	"MaxPlayers":       "最大玩家数",
	"ResetID":          "重置玩家ID",
	"SaveWorldEvery":   "世界自动保存间隔(分钟)",
	"BackupEvery":      "备份间隔(小时)",
	"BackupOnStart":    "启动时自动备份",
	"AllowNonAsciiUsername": "允许用户名使用非ASCII字符",
	"AllowSteamOnly":   "仅允许Steam登录",
	"SteamVAC":         "Steam VAC 反作弊",
	"SteamVACKick":     "VAC检测到后踢出玩家",
	"FastForwardModifier": "快进倍率",
	"DenyLoginOnOverloadedServer": "服务器过载时拒绝登录",
	"SafetyToggle":     "管理员安全模式开关",
	"SpawnSafehouseRaidProtection": "安全屋掠夺保护",

	// ---- 常规设置 ----
	"PauseEmpty":       "无玩家时暂停服务器",
	"GlobalChat":       "全局聊天",
	"ChatStreams":      "聊天频道流(全部/本地/阵营等)",
	"Open":             "允许进入服务器",
	"ServerWelcomeMessage": "服务器欢迎语",
	"DisplayUserName":  "显示玩家姓名",
	"DisplayServerName": "显示服务器名",
	"ServerName":       "服务器名称",
	"ServerPassword":   "服务器密码(留空为无密码)",
	"ShowHiddenOnJoin": "加入时显示隐藏设置",
	"HoursPerDay":      "每天小时数",
	"ShowPlayerBars":   "显示玩家状态条",
	"ShowPlayerNames":  "显示玩家名字",
	"ShowLifeStats":    "显示生存统计",
	"ShowSafety":       "显示安全状态",
	"ShowServerName":   "显示服务器名称",
	"ShowStats":        "显示统计信息",
	"ShowZombieCount":  "显示僵尸数量",
	"ShowZombieHealth": "显示僵尸血量",
	"ShowPlayerHealth": "显示玩家血量",
	"ShowSkillLevels":  "显示技能等级",
	"ShowPlayerPosition": "显示玩家坐标",
	"ShowPlayerFaction": "显示玩家阵营",
	"ShowPlayerGlobal": "显示玩家全局聊天",
	"ShowPlayerLocal":  "显示玩家本地聊天",

	// ---- 服务器与网络 ----
	"Port":             "游戏端口(UDP)",
	"DefaultPort":      "默认端口",
	"BindIP":           "监听IP",
	"Password":         "服务器密码",
	"PingLimit":        "Ping上限(毫秒)",
	"MaxPing":          "最大允许延迟",
	"MaxPlayersPerInstance": "每实例最大玩家数",
	"AllowCheats":      "允许作弊",
	"CoopMode":         "合作模式",
	"ServerSettingsMenu": "服务器设置菜单",
	"SteamPort":        "Steam端口",
	"SteamQueryPort":   "Steam查询端口",
	"DropLagouts":      "掉线玩家掉落物品",
	"DropOffline":      "离线玩家掉落物品",
	"DropOfflineMin":   "离线掉落最小时间",
	"DropOfflineMax":   "离线掉落最大时间",
	"DropOnSight":      "玩家视野内掉落",
	"SleepAllowed":     "允许睡觉",
	"Safehouse":        "允许安全屋",
	"SafehouseAllowLoot": "允许安全屋储物品",
	"SafehouseAllowRespawn": "允许安全屋重生",
	"SafehouseAllowFire": "允许安全屋用火",
	"SafehouseAllowFarming": "允许安全屋耕种",
	"SafehouseAllowDrink": "允许安全屋饮水",
	"SafehouseAllowFood": "允许安全屋食物",
	"SafehouseAllowFirstAid": "允许安全屋医疗",
	"SafehouseAllowLock": "允许安全屋上锁",
	"SafehouseAllowLog": "允许安全屋日志",
	"SafehouseAllowRefuel": "允许安全屋加油",

	// ---- 存档与模组 ----
	"WorkshopItems":    "创意工坊物品ID(分号分隔)",
	"Mods":             "模组ID(分号分隔)",
	"Map":              "地图",
	"MapChoices":       "地图选择",
	"ModFiles":         "模组文件",
	"WorkshopSites":    "创意工坊站点",
	"AutoCreateUserInWhiteList": "自动将加入玩家加入白名单",
	"WhiteList":        "白名单",
	"BannedPlayers":    "被封禁玩家",
	"DisableGlobalChat": "禁用全局聊天",
	"DisableRadio":     "禁用无线电",

	// ---- 随机事件与生成 ----
	"SpawnPoint":       "出生点",
	"SpawnZone":        "出生区域",
	"ZombieMaxPerPlayer": "每个玩家的最大僵尸数",
	"ZombieMax":        "最大僵尸数",
	"ZombieMaxRespawn": "僵尸重生数量",
	"ZombieRespawn":    "僵尸重生",
	"ZombieRespawnHours": "僵尸重生间隔(小时)",
	"ZombieRespawnStart": "僵尸重生开始时间",
	"ZombieRespawnStop": "僵尸重生停止时间",
	"ZombieRespawnDayLength": "僵尸重生周期(天)",
	"ZombieRespawnDayRespawn": "僵尸重生间隔(天)",
	"ZombieHordeSize":  "僵尸群规模",
	"ZombieHordeCap":   "僵尸群上限",
	"ZombieLore":       "僵尸特性",
	"ZombieLoreSpeed":  "僵尸速度",
	"ZombieLoreStrength": "僵尸力量",
	"ZombieLoreHearing": "僵尸听觉",
	"ZombieLoreMemory": "僵尸记忆",
	"ZombieLoreVision": "僵尸视觉",
	"ZombieLoreSmell":  "僵尸嗅觉",
	"ZombieLoreNightVision": "僵尸夜视",
	"ZombieLoreTransmission": "僵尸感染方式",
	"ZombieLoreGroup":  "僵尸聚集",
	"ZombieLoreGroupDistribution": "僵尸聚集分布",
	"ZombieLoreCognition": "僵尸认知",
	"ZombieLoreCrawlUnderVehicles": "僵尸可爬行穿过车辆底部",
	"ZombieLoreToxic":  "僵尸毒性",

	// ---- 玩法与难度 ----
	"Difficulty":       "难度",
	"DayLength":        "昼夜时长",
	"XpMultiplier":     "经验倍率",
	"FoodLootMultiplier": "食物物资倍率",
	"VehicleLootMultiplier": "车辆物资倍率",
	"SurvivalLootMultiplier": "生存物资倍率",
	"MedicalLootMultiplier": "医疗物资倍率",
	"MeleeLootMultiplier": "近战武器物资倍率",
	"FirearmLootMultiplier": "枪械物资倍率",
	"ToolLootMultiplier": "工具物资倍率",
	"BuildingLootMultiplier": "建材物资倍率",
	"FarmingLootMultiplier": "农业物资倍率",
	"OtherLootMultiplier": "其他物资倍率",
	"ErosionSpeed":     "环境侵蚀速度",
	"WaterShut":        "断水天数",
	"ElectricityShut":  "断电天数",
	"WaterAndElectricityShut": "水电切断天数",
	"GeneratorFuelComs": "发电机耗油",
	"GeneratorMaxFuel": "发电机最大油量",
	"GeneratorSpawn":   "发电机生成",
	"StarterKit":       "新手包",
	"PistolKit":        "手枪包",
	"RifleKit":         "步枪包",
	"ShotgunKit":       "霰弹枪包",
	"Sandbox":          "沙盒设置",
	"SandboxVars":      "沙盒变量",
	"SandboxOptions":   "沙盒选项",
	"SleepEvent":       "睡眠事件",
	"SleepEventOn":     "开启睡眠事件",
	"SleepEventMin":    "睡眠事件最短时长",
	"SleepEventMax":    "睡眠事件最长时长",
	"SleepEventMaxDist": "睡眠事件最大距离",
	"SleepEventSound":  "睡眠事件音效",
	"SleepEventSoundRadius": "睡眠事件音效范围",

	// ---- 聊天与广播 ----
	"ChatStreamsList":  "聊天频道列表",
	"ChatStreamsMuted": "静音的聊天频道",
	"ChatRadius":       "本地聊天半径",
	"ChatYellRadius":   "大喊聊天半径",
	"ChatWhisperRadius": "耳语聊天半径",
	"ChatShoutRadius":  "喊话聊天半径",
	"ChatMaxLength":    "聊天消息最大长度",
	"ChatTicksPerSecond": "聊天每秒更新次数",
	"ChatSensitiveMode": "聊天敏感词过滤",
	"ChatFilters":      "聊天过滤",
	"ChatFilterLevel":  "聊天过滤等级",

	// ---- 其他 ----
	"ID":               "服务器ID",
	"Comments":         "注释",
	"ShowConnectedPlayers": "显示在线玩家",
	"ShowDisconnectedPlayers": "显示离线玩家",
	"ShowPing":         "显示延迟",
	"ShowFPS":          "显示帧率",
	"ShowPingGraph":    "显示延迟曲线",
	"ShowChunkLoad":    "显示区块加载",
	"ShowChunkSave":    "显示区块保存",
	"ShowChunkUnload":  "显示区块卸载",
	"ShowChunkVisible": "显示区块可见",
	"ShowChunkStream":  "显示区块流",
	"ShowChunkUpdate":  "显示区块更新",
	"ShowChunkCreate":  "显示区块创建",
	"ShowChunkDelete":  "显示区块删除",
	"ShowChunkStreamBuffer": "显示区块流缓冲",
	"ShowChunkStreamBufferSize": "区块流缓冲大小",
	"ShowChunkStreamQueue": "区块流队列",
	"ShowChunkStreamQueueSize": "区块流队列大小",
	"ShowChunkStreamWorkQueue": "区块流工作队列",
	"ShowChunkStreamWorkQueueSize": "区块流工作队列大小",
	"ShowChunkStreamPool": "区块流池",
	"ShowChunkStreamPoolSize": "区块流池大小",
	"ShowChunkStreamPoolResize": "区块流池调整",
	"ShowChunkStreamPoolResizeSize": "区块流池调整大小",
	"ShowChunkStreamPoolOverflow": "区块流池溢出",
	"ShowChunkStreamPoolOverflowSize": "区块流池溢出大小",
}
