package config

// sandboxTooltipCN 补足 Build 42 中文翻译包中缺少的说明，并明确数值单位。
// 只在游戏原生 tooltip 为空时使用，避免覆盖官方说明。
var sandboxTooltipCN = map[string]string{
	"VERSION":                   "SandboxVars 配置格式版本号，由游戏管理；通常不要修改。",
	"Zombies":                   "僵尸数量预设。数值越高，世界中的僵尸越多。",
	"Distribution":              "僵尸分布预设。决定僵尸更均匀分布还是集中在城镇区域。",
	"DayLength":                 "一天的现实时间长度。选项单位为现实分钟/小时。",
	"StartYear":                 "世界开始年份，使用年份数字。",
	"WaterShutModifier":         "停水时间波动值，单位为游戏天；用于调整停水预设时间的随机范围。",
	"ElecShutModifier":          "停电时间波动值，单位为游戏天；用于调整停电预设时间的随机范围。",
	"AlarmDecayModifier":        "房屋警报电池衰减倍率。数值越高，停电后警报电池可维持的时间越短。",
	"InsaneLootFactor":          "极少物资倍率。相对正常物资倍率 1.0，0.05 表示约 5%。",
	"ExtremeLootFactor":         "特别稀少物资倍率，相对正常倍率 1.0。",
	"RareLootFactor":            "稀有物资倍率，相对正常倍率 1.0。",
	"NormalLootFactor":          "正常物资倍率基准，1.0 表示标准数量。",
	"CommonLootFactor":          "常见物资倍率，相对正常倍率 1.0。",
	"AbundantLootFactor":        "非常丰富物资倍率，相对正常倍率 1.0。",
	"Temperature":               "世界温度预设，数值越高通常越温暖。具体档位由游戏版本定义。",
	"Rain":                      "降雨量预设，数值越高降雨越频繁或更强。",
	"StatsDecrease":             "角色状态下降速度预设，影响饥饿、口渴、疲劳等状态。",
	"NatureAbundance":           "自然资源丰富度预设，影响可采集自然资源数量。",
	"Alarm":                     "房屋警报触发预设。决定未上锁房屋警报出现的概率或频率。",
	"LockedHouses":              "上锁房屋比例预设，数值越高越多房屋初始上锁。",
	"FoodRotSpeed":              "食物腐烂速度预设，数值越高腐烂越快。",
	"FridgeFactor":              "冰箱保鲜倍率，数值越低食物保存越久。",
	"EndRegen":                  "耐力回复速度预设，数值越高回复越快。",
	"CarAlarm":                  "车辆警报触发预设，数值越高更容易遇到带警报车辆。",
	"AnimalMilkIncModifier":     "动物产奶速度预设，影响挤奶间隔，单位由游戏内动物周期决定。",
	"AnimalWoolIncModifier":     "动物产毛速度预设，影响剪毛间隔，单位由游戏内动物周期决定。",
	"FishAbundance":             "鱼类丰富度预设，影响钓鱼获得鱼的概率和数量。",
	"GeneratorTileRange":        "发电机水平供电范围，单位为地图格（tiles）。",
	"Basement.SpawnFrequency":   "地下室内容刷新频率预设，数值越高刷新越频繁。",
	"Speed":                     "僵尸移动速度预设；具体数值含义会显示在下拉选项中。",
	"SprinterPercentage":        "冲刺僵尸比例，单位为百分比（0-100）。0 表示没有冲刺僵尸。",
	"Toughness":                 "僵尸耐久预设；具体数值含义会显示在下拉选项中。",
	"Transmission":              "感染传播方式预设；具体数值含义会显示在下拉选项中。",
	"Mortality":                 "感染致死时间预设，数值越高通常死亡更快；具体档位由游戏版本定义。",
	"Reanimate":                 "僵尸复生预设，决定尸体是否可能重新站起。",
	"Cognition":                 "僵尸认知预设，影响其开门、翻越和使用环境的能力。",
	"DoorOpeningPercentage":     "僵尸开门比例，单位为百分比（0-100）。",
	"CrawlUnderVehicle":         "僵尸爬过车辆底部的能力预设。",
	"Memory":                    "僵尸记忆预设，影响忘记玩家位置和声音来源的速度；具体档位见下拉选项。",
	"Sight":                     "僵尸视力预设；具体档位见下拉选项。",
	"Hearing":                   "僵尸听力预设；具体档位见下拉选项。",
	"PlayerSpawnZombieRemoval":  "玩家出生点清除僵尸预设，决定出生区域是否清除附近僵尸。",
	"PopulationMultiplier":      "僵尸人口倍率，相对基准 1.0；0.65 表示基准人口的 65%。",
	"PopulationStartMultiplier": "世界初始僵尸人口倍率，相对基准 1.0。",
	"PopulationPeakMultiplier":  "人口高峰倍率，相对基准 1.0。",
	"PopulationPeakDay":         "人口达到高峰的游戏天数，单位为游戏天。",
	"RespawnHours":              "僵尸重生检查间隔，单位为游戏小时；0 表示禁用。",
	"RespawnUnseenHours":        "未被玩家看见区域的重生间隔，单位为游戏小时；0 表示禁用。",
	"RespawnMultiplier":         "僵尸重生数量倍率，相对每次重生基准数量；0 表示不重生。",
	"RedistributeHours":         "僵尸重新分布间隔，单位为游戏小时。",
	"FollowSoundDistance":       "僵尸跟随声音的最大距离，单位为地图格（tiles）。",
	"RallyGroupSize":            "僵尸集群目标规模，单位为只。",
	"RallyGroupSizeVariance":    "集群规模随机波动，单位为百分比。",
	"RallyTravelDistance":       "集群移动距离，单位为地图格（tiles）。",
	"RallyGroupSeparation":      "集群之间的最小间隔，单位为地图格（tiles）。",
	"RallyGroupRadius":          "集群聚集半径，单位为地图格（tiles）。",
}

var sandboxTooltipOverrideCN = map[string]string{
	"SleepingEvent":      "玩家睡眠时发生噩梦、惊醒等事件的频率。1=永不，2=偶尔，3=经常。",
	"SirenShutoffHours":  "车辆警报器自动关闭前持续的时间，单位为游戏小时；范围 0-168。0 表示持续鸣响直到电池耗尽。",
	"WaterShutModifier":  "停水时间调整值，单位为游戏天；-1 表示使用游戏预设。",
	"ElecShutModifier":   "停电时间调整值，单位为游戏天；-1 表示使用游戏预设。",
	"AlarmDecayModifier": "停电后房屋警报电池可维持的时间，单位为游戏天；-1 表示使用游戏预设。",
}

var sandboxLabelOverrideCN = map[string]string{
	"WaterShutModifier":                   "停水时间调整（游戏天）",
	"ElecShutModifier":                    "停电时间调整（游戏天）",
	"AlarmDecayModifier":                  "警报电池调整（游戏天）",
	"SirenShutoffHours":                   "警报关闭时长（游戏小时）",
	"ZombieConfig.RespawnHours":           "僵尸重生间隔（游戏小时）",
	"ZombieConfig.RespawnUnseenHours":     "未巡视区重生间隔（游戏小时）",
	"ZombieConfig.RedistributeHours":      "僵尸重新分布间隔（游戏小时）",
	"ZombieConfig.FollowSoundDistance":    "跟随声音距离（地图格）",
	"ZombieConfig.RallyTravelDistance":    "集群移动距离（地图格）",
	"ZombieConfig.RallyGroupSeparation":   "集群分离距离（地图格）",
	"ZombieConfig.RallyGroupRadius":       "集群半径（地图格）",
	"ZombieConfig.RallyGroupSizeVariance": "集群规模波动（百分比）",
	"ZombieLore.SprinterPercentage":       "冲刺僵尸比例（百分比）",
	"ZombieLore.DoorOpeningPercentage":    "门开启比例（百分比）",
	"ZombieLore.Speed":                    "僵尸速度",
	"ZombieLore.Strength":                 "僵尸力量",
	"ZombieLore.Toughness":                "僵尸耐久",
	"ZombieLore.Transmission":             "感染传播方式",
	"ZombieLore.Mortality":                "感染致死时间",
	"ZombieLore.Reanimate":                "僵尸复生时间",
	"ZombieLore.Cognition":                "僵尸认知",
	"ZombieLore.Memory":                   "僵尸记忆",
	"ZombieLore.Sight":                    "僵尸视力",
	"ZombieLore.Hearing":                  "僵尸听力",
}
